import { lunesDe, diasDeLaSemana } from '@/lib/dominio/semana'
import { fechaLarga } from '@/lib/etiquetas'
import type { TablasFalsas } from '@/pruebas/supabase-falso'

/**
 * Datos de mentira para el modo demo.
 *
 * Existen para recorrer la aplicación sin base: la parrilla con piezas en cada
 * estado, el día con algo que aprobar, la bandeja con los tres motivos por los
 * que un comentario queda sin responder, y resultados con números que se
 * sostienen entre sí.
 *
 * Nada de esto viaja a producción. Vive tras MODO_DEMO y se arma en memoria.
 */

const SALEADS = '11111111-1111-4111-8111-111111111111'
const JUANADS = '22222222-2222-4222-8222-222222222222'

export const PERFIL_DEMO = 'aaaaaaaa-0000-4000-8000-000000000001'
const KAREN = 'aaaaaaaa-0000-4000-8000-000000000002'
const EMA = 'aaaaaaaa-0000-4000-8000-000000000003'
const OBSERVA = 'aaaaaaaa-0000-4000-8000-000000000004'

const IG_SALEADS = '33333333-3333-4333-8333-000000000001'
const TT_SALEADS = '33333333-3333-4333-8333-000000000002'
const YT_SALEADS = '33333333-3333-4333-8333-000000000003'
const IG_JUANADS = '33333333-3333-4333-8333-000000000004'

/** Una pieza por posición de la semana, para que la parrilla no quede coja. */
function pieza(n: number): string {
  return `44444444-4444-4444-8444-00000000000${n}`
}
function publicacion(n: number): string {
  return `55555555-5555-4555-8555-00000000000${n}`
}
function clave(n: number): string {
  return `66666666-6666-4666-8666-00000000000${n}`
}

const ahora = new Date()
const lunes = lunesDe(ahora)
const dias = diasDeLaSemana(lunes)
/** Fallback defensivo: diasDeLaSemana siempre devuelve siete, pero el tipo lo ignora. */
const dia = (i: number): string => dias[i] ?? lunes
const hoy = new Date().toISOString().slice(0, 10)

const haceHoras = (h: number) => new Date(ahora.getTime() - h * 3_600_000).toISOString()
const enDias = (d: number) => new Date(ahora.getTime() + d * 86_400_000).toISOString()

export function tablasDemo(): TablasFalsas {
  return {
    profiles: [
      {
        id: PERFIL_DEMO,
        nombre: 'Jess (demo)',
        email: 'demo@saleads.co',
        rol: 'editora',
        creado_at: haceHoras(720),
      },
      { id: KAREN, nombre: 'Karen', email: 'karen@saleads.co', rol: 'aprobadora', creado_at: haceHoras(700) },
      { id: EMA, nombre: 'Ema', email: 'ema@saleads.co', rol: 'audiovisual', creado_at: haceHoras(680) },
      { id: OBSERVA, nombre: 'Iván', email: 'ivan@saleads.co', rol: 'observador', creado_at: haceHoras(660) },
    ],

    brands: [
      {
        id: SALEADS,
        nombre: 'SaleADS',
        slug: 'saleads',
        sheet_id: '1DemoHojaDeCalculoSaleADS',
        sheet_tab: 'Hoja 1',
        mapa_columnas: {},
        whatsapp_url: 'https://wa.me/573000000000',
        creado_at: haceHoras(720),
      },
      {
        id: JUANADS,
        nombre: 'Juanads',
        slug: 'juanads',
        sheet_id: null,
        sheet_tab: 'Hoja 1',
        mapa_columnas: {},
        whatsapp_url: 'https://wa.me/573000000001',
        creado_at: haceHoras(720),
      },
    ],

    social_accounts: [
      {
        id: IG_SALEADS,
        brand_id: SALEADS,
        red: 'instagram',
        handle: '@saleads',
        external_account_id: '17841400000000001',
        credential_ref: 'META_TOKEN_SALEADS',
        token_expira_at: enDias(45),
        activa: true,
        publicacion_directa: false,
        cupo_respuestas_dia: null,
        creado_at: haceHoras(700),
      },
      {
        id: TT_SALEADS,
        brand_id: SALEADS,
        red: 'tiktok',
        handle: '@saleads',
        external_account_id: 'tt-saleads-0001',
        credential_ref: 'TIKTOK_TOKEN_SALEADS',
        token_expira_at: enDias(5),
        activa: true,
        // Sin la auditoría de Content Posting, el video va al buzón del creador.
        publicacion_directa: false,
        cupo_respuestas_dia: null,
        creado_at: haceHoras(700),
      },
      {
        id: YT_SALEADS,
        brand_id: SALEADS,
        red: 'youtube',
        handle: 'SaleADS',
        external_account_id: 'UCdemoSaleADS',
        credential_ref: 'YOUTUBE_TOKEN_SALEADS',
        token_expira_at: enDias(120),
        activa: true,
        publicacion_directa: false,
        cupo_respuestas_dia: 150,
        creado_at: haceHoras(700),
      },
      {
        id: IG_JUANADS,
        brand_id: JUANADS,
        red: 'instagram',
        handle: '@juanads',
        external_account_id: '17841400000000002',
        credential_ref: 'META_TOKEN_JUANADS',
        token_expira_at: enDias(60),
        activa: true,
        publicacion_directa: false,
        cupo_respuestas_dia: null,
        creado_at: haceHoras(700),
      },
    ],

    resources: [
      {
        id: '77777777-7777-4777-8777-000000000001',
        brand_id: SALEADS,
        titulo: 'Plantilla de campañas frías',
        descripcion: 'La estructura de campaña que usamos para arrancar de cero.',
        tipo: 'pdf',
        url: 'https://bio.saleads.co/recursos/plantilla-campanas',
        seccion: 'Empieza aquí',
        activo: true,
        creado_at: haceHoras(500),
      },
      {
        id: '77777777-7777-4777-8777-000000000002',
        brand_id: SALEADS,
        titulo: 'Calculadora de CPA',
        descripcion: 'Cuánto puedes pagar por lead sin perder plata.',
        tipo: 'html',
        url: 'https://bio.saleads.co/recursos/calculadora-cpa',
        seccion: 'Herramientas',
        activo: true,
        creado_at: haceHoras(300),
      },
      {
        id: '77777777-7777-4777-8777-000000000003',
        brand_id: JUANADS,
        titulo: 'Guion de primer contacto',
        descripcion: 'Qué decir en el primer mensaje de WhatsApp.',
        tipo: 'pdf',
        url: 'https://bio.saleads.co/recursos/guion-primer-contacto',
        seccion: 'Empieza aquí',
        activo: true,
        creado_at: haceHoras(120),
      },
    ],

    pieces: [
      {
        id: pieza(1),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'El error de bajar el presupuesto cuando el CPA sube',
        hook: 'Bajar el presupuesto cuando sube el CPA es la forma más cara de ahorrar',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoAAA/view',
        storage_path: `${SALEADS}/${pieza(1)}.mp4`,
        storage_expira_at: enDias(1),
        video_bytes: 48_200_000,
        video_error: null,
        caption_base:
          'Si el CPA sube y tu reacción es bajar el presupuesto, estás apagando el fuego con gasolina.',
        resource_id: '77777777-7777-4777-8777-000000000001',
        fecha_publicacion: dia(0),
        hora_publicacion: '18:00',
        responsable: 'Ema',
        estado: 'publicado',
        aprobada_por: KAREN,
        aprobada_at: haceHoras(72),
        origen: 'sheet',
        sheet_row_id: 'fila-2',
        sheet_hash: 'h1',
        sheet_pendiente: null,
        captions_red: { youtube: 'El error de bajar el presupuesto cuando el CPA sube #shorts' },
        creado_at: haceHoras(120),
        actualizado_at: haceHoras(40),
      },
      {
        id: pieza(2),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'Tres señales de que tu creativo está quemado',
        hook: 'Tu creativo no dejó de funcionar: tu audiencia dejó de verlo',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoBBB/view',
        storage_path: `${SALEADS}/${pieza(2)}.mp4`,
        storage_expira_at: enDias(1),
        video_bytes: 51_900_000,
        video_error: null,
        caption_base: 'Frecuencia arriba de 3, CTR cayendo y CPM estable. No es el algoritmo, es fatiga.',
        resource_id: '77777777-7777-4777-8777-000000000002',
        fecha_publicacion: dia(1),
        hora_publicacion: '19:00',
        responsable: 'Diego',
        estado: 'publicado',
        aprobada_por: KAREN,
        aprobada_at: haceHoras(60),
        origen: 'sheet',
        sheet_row_id: 'fila-3',
        sheet_hash: 'h2',
        sheet_pendiente: null,
        captions_red: {},
        creado_at: haceHoras(118),
        actualizado_at: haceHoras(20),
      },
      {
        id: pieza(3),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'Cómo leer el reporte de Meta en 5 minutos',
        hook: 'Miras 40 columnas y decides con 3',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoCCC/view',
        storage_path: null,
        storage_expira_at: null,
        video_bytes: null,
        video_error: null,
        caption_base: 'Frecuencia, CTR y CPA. El resto es ruido hasta que estas tres te dicen dónde mirar.',
        resource_id: '77777777-7777-4777-8777-000000000002',
        fecha_publicacion: hoy,
        hora_publicacion: '18:30',
        responsable: 'Ema',
        estado: 'aprobado',
        aprobada_por: KAREN,
        aprobada_at: haceHoras(6),
        origen: 'sheet',
        sheet_row_id: 'fila-4',
        sheet_hash: 'h3',
        sheet_pendiente: null,
        captions_red: {},
        creado_at: haceHoras(100),
        actualizado_at: haceHoras(6),
      },
      {
        id: pieza(4),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'Por qué tu público frío no convierte',
        hook: 'Le estás pidiendo matrimonio en la primera cita',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoDDD/view',
        storage_path: null,
        storage_expira_at: null,
        video_bytes: null,
        video_error: null,
        caption_base: 'El frío no compra. El frío te conoce. Vender viene después.',
        resource_id: '77777777-7777-4777-8777-000000000001',
        fecha_publicacion: hoy,
        hora_publicacion: '20:00',
        responsable: 'Iván',
        estado: 'aprobado',
        aprobada_por: KAREN,
        aprobada_at: haceHoras(5),
        origen: 'app',
        sheet_row_id: null,
        sheet_hash: null,
        sheet_pendiente: null,
        captions_red: { tiktok: 'El frío no compra. Te conoce. Vender viene después 👇' },
        creado_at: haceHoras(90),
        actualizado_at: haceHoras(5),
      },
      {
        id: pieza(5),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'El presupuesto mínimo para que Meta aprenda',
        hook: 'Con 5 dólares al día no estás probando: estás adivinando',
        formato: 'reel',
        drive_url: null,
        storage_path: null,
        storage_expira_at: null,
        video_bytes: null,
        // La pieza guarda el último error de Drive, tal como lo cuenta el manual.
        video_error: null,
        caption_base: null,
        resource_id: null,
        fecha_publicacion: dia(4),
        hora_publicacion: null,
        responsable: 'Diego',
        estado: 'revision',
        aprobada_por: null,
        aprobada_at: null,
        origen: 'sheet',
        sheet_row_id: 'fila-6',
        sheet_hash: 'h5',
        sheet_pendiente: null,
        captions_red: {},
        creado_at: haceHoras(80),
        actualizado_at: haceHoras(30),
      },
      {
        id: pieza(6),
        brand_id: SALEADS,
        semana: lunes,
        tema: 'Retargeting: a quién sí y a quién no',
        hook: 'Perseguir a todo el que pasó por tu web es quemar plata',
        formato: 'carrusel',
        drive_url: 'https://drive.google.com/file/d/1demoEEE/view',
        storage_path: null,
        storage_expira_at: null,
        video_bytes: null,
        video_error: 'La carpeta de Drive no está compartida con la cuenta de servicio',
        caption_base: 'Tres segundos en tu web no es interés. Es un scroll que se equivocó.',
        resource_id: null,
        fecha_publicacion: dia(5),
        hora_publicacion: '17:00',
        responsable: 'Ema',
        estado: 'borrador',
        aprobada_por: null,
        aprobada_at: null,
        origen: 'sheet',
        sheet_row_id: 'fila-7',
        sheet_hash: 'h6',
        // Un cambio de la hoja llegó con la pieza ya revisada, y espera confirmación.
        sheet_pendiente: {
          tema: 'Retargeting: a quién sí y a quién no (v2)',
          hook: 'No todo el que te visitó te quiere',
          sheet_hash: 'h6-nuevo',
          visto_at: haceHoras(2),
        },
        captions_red: {},
        creado_at: haceHoras(70),
        actualizado_at: haceHoras(2),
      },
      {
        id: pieza(7),
        brand_id: JUANADS,
        semana: lunes,
        tema: 'Lo que nadie te dice del primer mes vendiendo',
        hook: 'El primer mes no vendes: aprendes a quién le hablas',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoFFF/view',
        storage_path: `${JUANADS}/${pieza(7)}.mp4`,
        storage_expira_at: enDias(1),
        video_bytes: 39_400_000,
        video_error: null,
        caption_base: 'Si el primer mes esperabas ventas, te vendieron una expectativa, no un método.',
        resource_id: '77777777-7777-4777-8777-000000000003',
        fecha_publicacion: dia(2),
        hora_publicacion: '19:30',
        responsable: 'Iván',
        estado: 'publicado',
        aprobada_por: PERFIL_DEMO,
        aprobada_at: haceHoras(50),
        origen: 'app',
        sheet_row_id: null,
        sheet_hash: null,
        sheet_pendiente: null,
        captions_red: {},
        creado_at: haceHoras(110),
        actualizado_at: haceHoras(30),
      },
      {
        id: pieza(8),
        brand_id: JUANADS,
        semana: lunes,
        tema: 'El guion de WhatsApp que sí responde',
        hook: 'El lead no se enfrió: le escribiste como robot',
        formato: 'reel',
        drive_url: 'https://drive.google.com/file/d/1demoGGG/view',
        storage_path: null,
        storage_expira_at: null,
        video_bytes: null,
        video_error: null,
        caption_base: 'Tres líneas y una pregunta. Nada más.',
        resource_id: '77777777-7777-4777-8777-000000000003',
        fecha_publicacion: dia(3),
        hora_publicacion: '18:00',
        responsable: 'Ema',
        estado: 'fallido',
        aprobada_por: PERFIL_DEMO,
        aprobada_at: haceHoras(48),
        origen: 'app',
        sheet_row_id: null,
        sheet_hash: null,
        sheet_pendiente: null,
        captions_red: {},
        creado_at: haceHoras(105),
        actualizado_at: haceHoras(12),
      },
    ],

    keywords: [
      {
        id: clave(1),
        piece_id: pieza(1),
        palabra: 'PRESUPUESTO',
        variantes: ['PRESUPUESTOS', 'PRESUPUESTOO', 'PRESUPESTO'],
        activa_desde: haceHoras(40),
        activa_hasta: null,
        creado_at: haceHoras(120),
      },
      {
        id: clave(2),
        piece_id: pieza(2),
        palabra: 'CREATIVO',
        variantes: ['CREATIVOS', 'CREATIVOO', 'CREATVO'],
        activa_desde: haceHoras(20),
        activa_hasta: null,
        creado_at: haceHoras(118),
      },
      {
        id: clave(3),
        piece_id: pieza(3),
        palabra: 'REPORTE',
        variantes: ['REPORTES', 'REPORTEE'],
        activa_desde: null,
        activa_hasta: null,
        creado_at: haceHoras(100),
      },
      {
        id: clave(4),
        piece_id: pieza(4),
        palabra: 'FRIO',
        variantes: ['FRIOS', 'FRIOO'],
        activa_desde: null,
        activa_hasta: null,
        creado_at: haceHoras(90),
      },
      {
        id: clave(7),
        piece_id: pieza(7),
        palabra: 'METODO',
        variantes: ['METODOS', 'METODOO'],
        activa_desde: haceHoras(30),
        activa_hasta: null,
        creado_at: haceHoras(110),
      },
    ],

    dm_templates: [
      {
        id: '88888888-8888-4888-8888-000000000001',
        piece_id: pieza(1),
        mensaje: 'Te dejo la plantilla de campañas frías, tal como la usamos: {enlace}',
        cta_texto: 'Ver la plantilla',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+PRESUPUESTO',
        creado_at: haceHoras(120),
      },
      {
        id: '88888888-8888-4888-8888-000000000002',
        piece_id: pieza(2),
        mensaje: 'Aquí tienes la calculadora de CPA que menciono en el video: {enlace}',
        cta_texto: 'Abrir la calculadora',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+CREATIVO',
        creado_at: haceHoras(118),
      },
      {
        id: '88888888-8888-4888-8888-000000000003',
        piece_id: pieza(3),
        mensaje: 'Te mando el resumen de las 3 columnas que sí importan: {enlace}',
        cta_texto: 'Ver el resumen',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+REPORTE',
        creado_at: haceHoras(100),
      },
      {
        id: '88888888-8888-4888-8888-000000000004',
        piece_id: pieza(4),
        mensaje: 'Te dejo la estructura para público frío: {enlace}',
        cta_texto: 'Ver la estructura',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+FRIO',
        creado_at: haceHoras(90),
      },
      {
        id: '88888888-8888-4888-8888-000000000007',
        piece_id: pieza(7),
        mensaje: 'Te comparto el guion de primer contacto: {enlace}',
        cta_texto: 'Ver el guion',
        destino_url: 'https://wa.me/573000000001?text=Hola%2C+vengo+por+METODO',
        creado_at: haceHoras(110),
      },
    ],

    tracked_links: [
      {
        id: '99999999-9999-4999-8999-000000000001',
        piece_id: pieza(1),
        slug: 'presupuesto-444444',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+PRESUPUESTO',
        clics: 87,
        creado_at: haceHoras(120),
      },
      {
        id: '99999999-9999-4999-8999-000000000002',
        piece_id: pieza(2),
        slug: 'creativo-444444',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+CREATIVO',
        clics: 41,
        creado_at: haceHoras(118),
      },
      {
        id: '99999999-9999-4999-8999-000000000003',
        piece_id: pieza(3),
        slug: 'reporte-444444',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+REPORTE',
        clics: 0,
        creado_at: haceHoras(100),
      },
      {
        id: '99999999-9999-4999-8999-000000000004',
        piece_id: pieza(4),
        slug: 'frio-444444',
        destino_url: 'https://wa.me/573000000000?text=Hola%2C+vengo+por+FRIO',
        clics: 0,
        creado_at: haceHoras(90),
      },
      {
        id: '99999999-9999-4999-8999-000000000007',
        piece_id: pieza(7),
        slug: 'metodo-444444',
        destino_url: 'https://wa.me/573000000001?text=Hola%2C+vengo+por+METODO',
        clics: 23,
        creado_at: haceHoras(110),
      },
    ],

    publications: [
      {
        id: publicacion(1),
        piece_id: pieza(1),
        social_account_id: IG_SALEADS,
        caption_final:
          'Si el CPA sube y tu reacción es bajar el presupuesto, estás apagando el fuego con gasolina.',
        estado: 'publicado',
        external_post_id: 'ig-post-demo-0001',
        container_id: null,
        permalink: 'https://www.instagram.com/reel/DemoPresupuesto/',
        publicado_at: haceHoras(40),
        programado_at: haceHoras(40),
        intentos: 1,
        proximo_intento_at: null,
        ultimo_error: null,
        creado_at: haceHoras(48),
        actualizado_at: haceHoras(40),
      },
      {
        id: publicacion(2),
        piece_id: pieza(1),
        social_account_id: YT_SALEADS,
        caption_final: 'El error de bajar el presupuesto cuando el CPA sube #shorts',
        estado: 'publicado',
        external_post_id: 'yt-demo-0001',
        container_id: null,
        permalink: 'https://www.youtube.com/shorts/ytdemo0001',
        publicado_at: haceHoras(40),
        programado_at: haceHoras(40),
        intentos: 1,
        proximo_intento_at: null,
        ultimo_error: null,
        creado_at: haceHoras(48),
        actualizado_at: haceHoras(40),
      },
      {
        id: publicacion(3),
        piece_id: pieza(1),
        social_account_id: TT_SALEADS,
        caption_final: 'Si el CPA sube y bajas el presupuesto, apagas el fuego con gasolina.',
        estado: 'pendiente',
        external_post_id: 'tt-publish-demo-0001',
        container_id: null,
        permalink: null,
        publicado_at: null,
        programado_at: haceHoras(40),
        intentos: 1,
        proximo_intento_at: null,
        ultimo_error: 'El video llegó al buzón de TikTok. Se suelta desde la app del creador.',
        creado_at: haceHoras(48),
        actualizado_at: haceHoras(40),
      },
      {
        id: publicacion(4),
        piece_id: pieza(2),
        social_account_id: IG_SALEADS,
        caption_final: 'Frecuencia arriba de 3, CTR cayendo y CPM estable. No es el algoritmo, es fatiga.',
        estado: 'publicado',
        external_post_id: 'ig-post-demo-0002',
        container_id: null,
        permalink: 'https://www.instagram.com/reel/DemoCreativo/',
        publicado_at: haceHoras(20),
        programado_at: haceHoras(20),
        intentos: 1,
        proximo_intento_at: null,
        ultimo_error: null,
        creado_at: haceHoras(30),
        actualizado_at: haceHoras(20),
      },
      {
        id: publicacion(5),
        piece_id: pieza(7),
        social_account_id: IG_JUANADS,
        caption_final: 'Si el primer mes esperabas ventas, te vendieron una expectativa, no un método.',
        estado: 'publicado',
        external_post_id: 'ig-post-demo-0003',
        container_id: null,
        permalink: 'https://www.instagram.com/reel/DemoMetodo/',
        publicado_at: haceHoras(30),
        programado_at: haceHoras(30),
        intentos: 1,
        proximo_intento_at: null,
        ultimo_error: null,
        creado_at: haceHoras(40),
        actualizado_at: haceHoras(30),
      },
      {
        id: publicacion(6),
        piece_id: pieza(8),
        social_account_id: IG_JUANADS,
        caption_final: 'Tres líneas y una pregunta. Nada más.',
        estado: 'fallido',
        external_post_id: null,
        container_id: 'ig-container-demo-0009',
        permalink: null,
        publicado_at: null,
        programado_at: haceHoras(12),
        intentos: 3,
        proximo_intento_at: null,
        ultimo_error: 'El video sigue en proceso después de dos minutos',
        creado_at: haceHoras(24),
        actualizado_at: haceHoras(12),
      },
    ],

    comments: [
      // Respondidos: el camino feliz, en las dos marcas.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000001',
        publication_id: publicacion(1),
        external_comment_id: 'ig-c-0001',
        autor_username: 'andrea.mkt',
        autor_external_id: 'ig-user-0001',
        texto: 'PRESUPUESTO por favor 🙏',
        keyword_id: clave(1),
        estado: 'respondido',
        motivo: null,
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(38),
        respondido_at: haceHoras(38),
      },
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000002',
        publication_id: publicacion(1),
        external_comment_id: 'ig-c-0002',
        autor_username: 'julian.ads',
        autor_external_id: 'ig-user-0002',
        texto: 'quiero el PRESUPUESTOO, me sirve muchísimo',
        keyword_id: clave(1),
        estado: 'respondido',
        motivo: null,
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(37),
        respondido_at: haceHoras(37),
      },
      // Mismo autor, segunda vez: una sola respuesta por publicación.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000003',
        publication_id: publicacion(1),
        external_comment_id: 'ig-c-0003',
        autor_username: 'andrea.mkt',
        autor_external_id: 'ig-user-0001',
        texto: 'PRESUPUESTO otra vez, no me llegó',
        keyword_id: clave(1),
        estado: 'ignorado',
        motivo: 'el autor ya recibió respuesta',
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(36),
        respondido_at: null,
      },
      // Sin la palabra: ni se toca.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000004',
        publication_id: publicacion(1),
        external_comment_id: 'ig-c-0004',
        autor_username: 'pedro.growth',
        autor_external_id: 'ig-user-0004',
        texto: 'buenísimo el video, muy claro 👏',
        keyword_id: null,
        estado: 'ignorado',
        motivo: null,
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(35),
        respondido_at: null,
      },
      // Bandeja · ventana de 7 días vencida.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000005',
        publication_id: publicacion(1),
        external_comment_id: 'ig-c-0005',
        autor_username: 'lucia.ecom',
        autor_external_id: 'ig-user-0005',
        texto: 'hola! me pasas el PRESUPUESTO?',
        keyword_id: clave(1),
        estado: 'manual_pendiente',
        motivo: 'ventana_vencida',
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: new Date(ahora.getTime() - 9 * 86_400_000).toISOString(),
        respondido_at: null,
      },
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000006',
        publication_id: publicacion(4),
        external_comment_id: 'ig-c-0006',
        autor_username: 'marcela.dp',
        autor_external_id: 'ig-user-0006',
        texto: 'CREATIVO 🔥🔥',
        keyword_id: clave(2),
        estado: 'respondido',
        motivo: null,
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(18),
        respondido_at: haceHoras(18),
      },
      // Bandeja · la plataforma rechazó el envío y quedó esperando su turno.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000007',
        publication_id: publicacion(4),
        external_comment_id: 'ig-c-0007',
        autor_username: 'santiago.perf',
        autor_external_id: 'ig-user-0007',
        texto: 'me mandas lo del CREATIVO porfa',
        keyword_id: clave(2),
        estado: 'fallido',
        motivo: '(#613) Calls to this api have exceeded the rate limit',
        intentos_dm: 2,
        proximo_intento_at: new Date(ahora.getTime() + 8 * 60_000).toISOString(),
        detectado_at: haceHoras(1),
        respondido_at: null,
      },
      // Bandeja · TikTok no tiene API de respuesta.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000008',
        publication_id: publicacion(3),
        external_comment_id: 'tt-c-0001',
        autor_username: 'dani.tiktok',
        autor_external_id: 'tt-user-0001',
        texto: 'PRESUPUESTO 👀',
        keyword_id: clave(1),
        estado: 'manual_pendiente',
        motivo: 'la red carece de API de respuesta',
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(10),
        respondido_at: null,
      },
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000009',
        publication_id: publicacion(5),
        external_comment_id: 'ig-c-0009',
        autor_username: 'carolina.vende',
        autor_external_id: 'ig-user-0009',
        texto: 'necesito el METODO 🙌',
        keyword_id: clave(7),
        estado: 'respondido',
        motivo: null,
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(28),
        respondido_at: haceHoras(28),
      },
      // Bandeja · el cupo diario de YouTube se agotó.
      {
        id: 'bbbbbbbb-0000-4000-8000-000000000010',
        publication_id: publicacion(2),
        external_comment_id: 'yt-c-0001',
        autor_username: 'Camilo R.',
        autor_external_id: 'yt-user-0001',
        texto: 'Me interesa el PRESUPUESTO, ¿cómo lo consigo?',
        keyword_id: clave(1),
        estado: 'manual_pendiente',
        motivo: 'cupo diario de la plataforma agotado',
        intentos_dm: 0,
        proximo_intento_at: null,
        detectado_at: haceHoras(4),
        respondido_at: null,
      },
    ],

    dm_log: [
      {
        id: 'cccccccc-0000-4000-8000-000000000001',
        comment_id: 'bbbbbbbb-0000-4000-8000-000000000001',
        destinatario: 'andrea.mkt',
        mensaje:
          'Te dejo la plantilla de campañas frías, tal como la usamos: https://bio.saleads.co/r/presupuesto-444444',
        estado: 'enviado',
        enviado_at: haceHoras(38),
        error: null,
      },
      {
        id: 'cccccccc-0000-4000-8000-000000000002',
        comment_id: 'bbbbbbbb-0000-4000-8000-000000000002',
        destinatario: 'julian.ads',
        mensaje:
          'Te dejo la plantilla de campañas frías, tal como la usamos: https://bio.saleads.co/r/presupuesto-444444',
        estado: 'enviado',
        enviado_at: haceHoras(37),
        error: null,
      },
      {
        id: 'cccccccc-0000-4000-8000-000000000003',
        comment_id: 'bbbbbbbb-0000-4000-8000-000000000006',
        destinatario: 'marcela.dp',
        mensaje:
          'Aquí tienes la calculadora de CPA que menciono en el video: https://bio.saleads.co/r/creativo-444444',
        estado: 'enviado',
        enviado_at: haceHoras(18),
        error: null,
      },
      {
        id: 'cccccccc-0000-4000-8000-000000000004',
        comment_id: 'bbbbbbbb-0000-4000-8000-000000000007',
        destinatario: 'santiago.perf',
        mensaje:
          'Aquí tienes la calculadora de CPA que menciono en el video: https://bio.saleads.co/r/creativo-444444',
        estado: 'fallido',
        enviado_at: haceHoras(1),
        error: '(#613) Calls to this api have exceeded the rate limit',
      },
      {
        id: 'cccccccc-0000-4000-8000-000000000005',
        comment_id: 'bbbbbbbb-0000-4000-8000-000000000009',
        destinatario: 'carolina.vende',
        mensaje: 'Te comparto el guion de primer contacto: https://bio.saleads.co/r/metodo-444444',
        estado: 'enviado',
        enviado_at: haceHoras(28),
        error: null,
      },
    ],

    approvals: [
      {
        id: 'dddddddd-0000-4000-8000-000000000001',
        piece_id: pieza(1),
        usuario_id: KAREN,
        accion: 'aprobar',
        comentario: null,
        creado_at: haceHoras(72),
      },
      {
        id: 'dddddddd-0000-4000-8000-000000000002',
        piece_id: pieza(5),
        usuario_id: KAREN,
        accion: 'devolver',
        comentario: 'El hook se pisa con el de la pieza del martes. Cámbialo y vuelve a subirla.',
        creado_at: haceHoras(30),
      },
    ],

    notices: [
      {
        id: 'eeeeeeee-0000-4000-8000-000000000001',
        tipo: 'pieza_devuelta',
        titulo: 'Volvió a revisión: El presupuesto mínimo para que Meta aprenda',
        detalle: 'El hook se pisa con el de la pieza del martes. Cámbialo y vuelve a subirla.',
        brand_id: SALEADS,
        piece_id: pieza(5),
        clave: 'devuelta:demo-0001',
        leido_at: null,
        creado_at: haceHoras(30),
      },
      {
        id: 'eeeeeeee-0000-4000-8000-000000000002',
        tipo: 'borrador_tiktok',
        titulo: '"El error de bajar el presupuesto cuando el CPA sube" espera en el buzón de TikTok',
        detalle: 'El video llegó al buzón de TikTok. Se suelta desde la app del creador.',
        brand_id: SALEADS,
        piece_id: pieza(1),
        clave: 'borrador:demo-0001',
        leido_at: null,
        creado_at: haceHoras(40),
      },
      {
        id: 'eeeeeeee-0000-4000-8000-000000000003',
        tipo: 'token_por_vencer',
        titulo: `El acceso de @saleads vence el ${fechaLarga(enDias(5).slice(0, 10))}`,
        detalle: 'Renueva el token de tiktok antes de esa fecha para que la cuenta siga publicando.',
        brand_id: SALEADS,
        piece_id: null,
        clave: 'token:demo-tiktok',
        leido_at: null,
        creado_at: haceHoras(8),
      },
      {
        id: 'eeeeeeee-0000-4000-8000-000000000004',
        tipo: 'publicacion_fallida',
        titulo: '"El guion de WhatsApp que sí responde" no salió en instagram',
        detalle: 'El video sigue en proceso después de dos minutos',
        brand_id: JUANADS,
        piece_id: pieza(8),
        clave: 'fallida:demo-0001',
        leido_at: null,
        creado_at: haceHoras(12),
      },
      {
        id: 'eeeeeeee-0000-4000-8000-000000000005',
        tipo: 'publicacion_fallida',
        titulo: 'El video de "Retargeting: a quién sí y a quién no" no se pudo bajar de Drive',
        detalle: 'La carpeta de Drive no está compartida con la cuenta de servicio',
        brand_id: SALEADS,
        piece_id: pieza(6),
        clave: 'video:demo-0001',
        leido_at: haceHoras(3),
        creado_at: haceHoras(20),
      },
    ],

    sync_logs: [
      {
        id: 'ffffffff-0000-4000-8000-000000000001',
        brand_id: SALEADS,
        filas_leidas: 9,
        filas_creadas: 0,
        filas_actualizadas: 1,
        filas_ignoradas: 2,
        detalle: [
          { fila: 'fila-9', motivo: 'la fila llega sin tema' },
          { fila: 'fila-10', motivo: 'la fecha "12 sep" no se entiende' },
          {
            fila: 'fila-7',
            motivo: 'la hoja cambió con la pieza ya aprobada, el cambio espera confirmación',
          },
        ],
        corrio_at: haceHoras(0.2),
      },
    ],

    calendar_proposals: [
      {
        id: 'aaaabbbb-0000-4000-8000-000000000001',
        brand_id: SALEADS,
        semana: lunes,
        propuesta: [
          { id: pieza(3), fecha: dia(0), tema: 'Cómo leer el reporte de Meta en 5 minutos' },
          { id: pieza(4), fecha: dia(1), tema: 'Por qué tu público frío no convierte' },
          { id: pieza(6), fecha: dia(2), tema: 'Retargeting: a quién sí y a quién no' },
        ],
        motivo: 'una pieza volvió a revisión',
        creada_por: KAREN,
        creada_at: haceHoras(30),
        aplicada_at: null,
      },
    ],
  }
}
